marvel_core:
    resource: "@MarvelCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
marvel_characters:
    resource: "@MarvelCharactersBundle/Resources/config/routing.yml"
    prefix:   /characters    


